-- 코드를 작성해주세요
SELECT A.ID, 
    IFNULL(B.CNT, 0) CHILD_COUNT
FROM ECOLI_DATA A 
    LEFT JOIN (
        SELECT PARENT_ID, COUNT(*) CNT
        FROM ECOLI_DATA
        GROUP BY PARENT_ID) B ON A.ID = B.PARENT_ID
ORDER BY A.ID