-- 코드를 작성해주세요
SELECT 
    COUNT(*) FISH_COUNT,
    MAX(A.LENGTH) MAX_LENGTH,
    A.FISH_TYPE FISH_TYPE
FROM (
SELECT 
    FISH_TYPE,
    CASE
        WHEN LENGTH IS NULL THEN 10
        WHEN LENGTH <= 10 THEN 10
        WHEN LENGTH > 10 THEN LENGTH
    END LENGTH
FROM FISH_INFO) A
GROUP BY A.FISH_TYPE
HAVING AVG(A.LENGTH) >= 33
ORDER BY FISH_TYPE
